import { defineConfig, presetAttributify, presetUno, presetIcons } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  safelist: [
    'logos-cursor',
    'logos-visual-studio-code',
    'logos-github-icon',
    'logos-postgresql',
    'logos-anthropic',
    'logos-anthropic-icon',
    'logos-zed',
    'logos-neovim',
    'logos-webstorm',
    'simple-icons-openai',
    'i-cib-google-cloud',
    'i-carbon-tool-kit',
    'i-carbon-add',
    'i-carbon-arrow-right',
    'i-carbon-warning-alt',
    'i-carbon-close-filled',
    'i-carbon-checkmark-filled',
    'i-carbon-security',
    'i-carbon-growth',
    'i-carbon-search',
    'i-carbon-code',
    'i-carbon-idea-filled',
    'i-carbon-folder-details',
    'i-carbon-database',
    'i-carbon-tools-alt',
    'i-carbon-earth-filled',
    'i-carbon-terminal-3270',
    'i-carbon-idea',
    'i-carbon-connect',
    'i-carbon-connection',
    'i-carbon-help',
    'i-carbon-presentation-file',
    'i-carbon-document-pdf',
    'i-carbon-user-profile',
    'i-carbon-document',
    'i-carbon-calendar',
    'i-carbon-flow',
    'i-carbon-cloud',
    'i-carbon-warning',
    'i-carbon-globe',
    'i-carbon-collaborate',
    'i-carbon-store',
    'i-logos-github-icon',
    'i-logos-slack-icon',
  ],
}) 